name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test-report:
    runs-on: ubuntu-latest

    steps:
      # 1. Fazer checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configurar JDK
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17' # Alinhado ao projeto (Java 17)
          distribution: 'temurin'

      # 3. Instalar dependências e compilar o projeto
      - name: Build with Maven
        run: mvn clean install

      # 4. Publicar os relatórios de testes (Surefire Reports)
      - name: Publish test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/surefire-reports/

      # 5. Publicar relatório de cobertura Jacoco
      - name: Publish Jacoco Coverage Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/